apiVersion: v1
kind: Secret
metadata:
  name: hf-token-secret
  namespace: cosmos
  labels:
    app: cosmos
type: Opaque
data:
  # Base64 encoded HuggingFace token
  # To encode: echo -n "your-hf-token" | base64
  # To be replaced with actual token during deployment
  HF_TOKEN: REPLACE_WITH_BASE64_ENCODED_TOKEN
