apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-model-storage
  namespace: cosmos
  labels:
    app: cosmos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 150Gi  # Default size, adjust as needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cosmos-cache-storage
  namespace: cosmos
  labels:
    app: cosmos
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 100Gi  # Default size, adjust as needed
