apiVersion: v1
kind: Service
metadata:
  name: cosmos-service
  namespace: cosmos
  labels:
    app: cosmos
spec:
  type: LoadBalancer
  selector:
    app: cosmos
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
