apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cosmos

resources:
  - 00-namespace.yaml
  - 01-secret.yaml
  - 02-configmap.yaml
  - 03-pvcs.yaml
  - 04-deployment.yaml
  - 05-service.yaml
  - 06-hpa.yaml
  - 07-pdb.yaml

# Common labels to be applied to all resources
commonLabels:
  app.kubernetes.io/name: cosmos
  app.kubernetes.io/part-of: cosmos-inference

# Patches for customization
patches:
  # Example patch to update replicas
  - target:
      kind: Deployment
      name: cosmos-inference
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  # Example patch to update GPU type
  - target:
      kind: Deployment
      name: cosmos-inference
    patch: |-
      - op: replace
        path: /spec/template/spec/nodeSelector/cloud.google.com~1gke-accelerator
        value: nvidia-l4

# Configuration for different environments can be managed with overlays
# See kubernetes/overlays/prod and kubernetes/overlays/dev directories
